name: Build FAP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          task: build
          app-dir: eth_tester
